### ISSUE TITLE
Inner product in the Python bindings is accidentally implemented as outer product

### ISSUE THREAD

**Issue by hugohadfield** [vincentnozick/garamon#5]
Looking at https://github.com/vincentnozick/garamon/blob/f247faf192d85cd4cacd5df98a67eae02d7fdec2/data/PythonBindings.cpp#L78
Suggests that the syntax A|B is equivalent to A^B, presumably this is just a little typo!

**Comment by hugohadfield** [comment]
One useful thing we could do at some point is to set up a CI build that runs garamon python bindings and clifford and tests them against one another, would be useful for both libraries I imagine!

**Comment by sbreuils** [comment]
Thank you very much for the suggestions! I think it is fixed now.

**Comment by sbreuils** [comment]
In a near future commit, I will also add a python sample.
This would be the equivalent of the c++ sample but for the python binding.
For C3GA, this will look like that
``` python
from c3ga_py import *

mv1 = Mvec();
mv1[scalar] = 1.0;
mv1[E0] = 42.0;
print("mv1 : ", mv1 )

mv2 = Mvec()
mv2[E0] = 1.0;
mv2[E1] = 2.0;
mv2 += e0123i() + 2*e01();
print("mv2 : " , mv2 );

# some products
print("outer product     : ", (mv1 ^ mv2) )
print("inner product     : ", (mv1 | mv2) )
print("geometric product     : ", (mv1 * mv2) )


# some tools
print("grade : ", mv1.grade())
print("norm : ", mv1.norm())
print("norm : ", mv2.grade())
```

**Comment by sbreuils** [comment]
Yes, this would be very interesting to test both libraries!
