### ISSUE TITLE
Followup for issue 4.  Other eigen assertion.

### ISSUE THREAD

**Issue by peeterjoot** [vincentnozick/garamon#7]
With issue #4 fixed, continuing execution of the sample code hits the following assertion:

`mv1: -3120.65 + 9066.51*e1 + 17022*e2 + 73008.7*e12
mv2: 5*e1 - 5*e2
bug: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:425: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
Aborted`

The line that kills things was:

mv3 = mv1.outerPrimalDual(mv2);    // fast version of mv3 = mv1 ^ mv2.dual();

Reproducer is attached.
[bug.zip](https://github.com/vincentnozick/garamon/files/5727830/bug.zip)

g++ -std=c++17 -Wall -Werror -MMD -g -I/usr/include/eigen3 -Wno-error=unused-variable   -c -o bug.o bug.cc
g++ -o bug -std=c++17 -Wall -Werror -MMD -g -I/usr/include/eigen3 -Wno-error=unused-variable bug.o -le3ga

**Comment by sbreuils** [comment]
Thanks! And the same error should also apply for outerDualPrimal.
I will fix this today (22nd) a bit later in the end of the afternoon (JST) and let you know.

**Comment by sbreuils** [comment]
There were default parameters that did not depend on the vector space dimension whereas they should. Now, it should be fixed!

**Comment by peeterjoot** [comment]
Thanks.  I'm now able to successfully run simple test programs for both e2ga and e3ga: https://github.com/peeterjoot/physicsplay/tree/master/programming/garamon
